apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
spec:
  selector:
    matchLabels:
      name: helloweb
  replicas: 10
  template:
    metadata:
      labels:
        name: helloweb
    spec:
      containers:
      - name: helloweb
        image: findvikas/helloweb:v0.6
        imagePullPolicy: IfNotPresent
        env:
        - name: BUILD
          value: "Mon Aug 12 05:57:28 UTC 2019"
        - name: VERSION
          value: "v0.6"
        ports:
        - containerPort: 3000